# Generated by Django 3.2 on 2024-01-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='weeklybudget',
            name='end_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='yearlybudget',
            name='end_date',
            field=models.DateField(default=None),
        ),
    ]
