# Generated by Django 3.2 on 2024-01-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20240120_1944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name_plural': 'Expense Categories'},
        ),
        migrations.AlterModelOptions(
            name='incomecategory',
            options={'verbose_name_plural': 'Income Categories'},
        ),
    ]
