# Generated by Django 3.2 on 2024-01-19 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_auto_20240119_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlybudget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='weeklybudget',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='yearlybudget',
            name='end_date',
        ),
    ]
