# Generated by Django 3.2 on 2024-01-18 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20240118_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_recurring',
        ),
    ]
