# Generated by Django 3.2 on 2024-01-19 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_auto_20240119_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybudget',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklybudget',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yearlybudget',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
