# Generated by Django 3.2 on 2024-01-20 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='typicalIncome',
            new_name='ExpenseCategory',
        ),
        migrations.RenameModel(
            old_name='typicalExpense',
            new_name='IncomeCategory',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='typical_expense',
        ),
        migrations.RemoveField(
            model_name='income',
            name='typical_income',
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.expensecategory'),
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='transactions.incomecategory'),
        ),
    ]
