# Generated by Django 3.2 on 2024-01-22 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transactions', '0005_debtdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('SAVINGS', 'Savings Account'), ('LOW_RISK', 'Low Risk Investment'), ('MEDIUM_RISK', 'Medium Risk Investment'), ('HIGH_RISK', 'High Risk Investment')], max_length=50)),
                ('min_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Invest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('investment_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.investmentoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
