# Generated by Django 3.2 on 2024-01-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleacademy',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Suspended'), (2, 'Active')], default=0),
        ),
    ]
